baseURL = 'https://blog.libromarko.xyz/'
languageCode = 'en-us'
title = ''
theme = "moments"
paginate = 10
paginatePath = '.'

[params]
    title = "Blog"
    signature = ""
    cover = "/img/blog.png"
    name = "libromarko"
    avatar = "/img/play_store_512.png"
